# 1. Builder stage
FROM maven:3.9.3-jdk-21 AS builder
WORKDIR /app

COPY mvnw mvnw.cmd pom.xml ./
COPY .mvn .mvn
RUN chmod +x mvnw

RUN ./mvnw dependency:go-offline -B

COPY src src
RUN ./mvnw clean package -DskipTests

# 2. Runtime stage
FROM openjdk:21-jdk-slim
WORKDIR /app

COPY --from=builder /app/target/*-runner.jar app.jar
EXPOSE 8080
CMD ["java", "-jar", "app.jar"]
