# Builder
FROM registry.access.redhat.com/ubi9/openjdk-21:1.23 AS builder
WORKDIR /app

# Copy Maven wrapper and pom.xml first
COPY mvnw mvnw.cmd pom.xml ./
COPY .mvn .mvn

# Pre-download dependencies (this step will be cached until pom.xml changes)
RUN ./mvnw dependency:go-offline -B

# Now copy the source
COPY src src

# Build the application
RUN ./mvnw clean package -DskipTests
